source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DevContactSDK_Example', :exclusive => true do
  pod "DevContactSDK", :path => "../"
end

target 'DevContactSDK_Tests', :exclusive => true do
    pod "DevContactSDK", :path => "../"
end
